### ISSUE TITLE
We can not use option `ignoreAssets` and `yaml` both when use lambda

### ISSUE THREAD

**Issue by ncaq** [hupe1980/jest-cdk-snapshot#10]
I use `toMatchCdkSnapshot` with option of `ignoreAssets` and `yaml`.

I got exception.

~~~
  ● Snapshot

    YAMLException: unacceptable kind of an object to dump [object Function]

      13 | 
      14 | test("Snapshot", () => {
    > 15 |   expect(stack).toMatchCdkSnapshot({
         |                 ^
      16 |     ignoreAssets: true,
      17 |     yaml: true,
      18 |   });

      at writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:779:13)
      at writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
      at writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
      at writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
      at writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
      at writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
      at writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
      at writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
      at writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
      at writeBlockMapping (node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
      at writeNode (node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
      at dump (node_modules/js-yaml/lib/js-yaml/dumper.js:840:7)
      at Object.safeDump (node_modules/js-yaml/lib/js-yaml/dumper.js:846:10)
      at convertStack (node_modules/jest-cdk-snapshot/src/index.ts:93:24)
      at Object.<anonymous>.exports.toMatchCdkSnapshot (node_modules/jest-cdk-snapshot/src/index.ts:49:17)
      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:342:30)
      at Object.throwingMatcher [as toMatchCdkSnapshot] (node_modules/expect/build/index.js:343:15)
      at Object.<anonymous> (test/aws-cost-watcher.test.ts:15:17)
~~~

I use [aws-lambda-nodejs module · AWS CDK](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html).

**Comment by fractionalJoe** [comment]
I see this one has been open for a while. Any update?

**Comment by ncaq** [comment]
> I see this one has been open for a while. Any update?
None.

**Comment by exoego** [comment]
Opened https://github.com/hupe1980/jest-cdk-snapshot/pull/30
